-- Migration 046: Indian placement-tier interview questions
-- Service tier (TCS/Infosys/Wipro) genuinely easy per research — "nothing
-- LeetCode hard," basic DSA + separate aptitude/CS-fundamentals rounds
-- this platform doesn't cover. Product tier (Flipkart/Swiggy/Paytm)
-- genuine medium DSA, closer to the existing US big-tech set.
-- All LeetCode URLs individually verified via live search on 2026-09-14.

INSERT INTO interview_questions
  (concept_id, question_type, company, prompt, difficulty, company_note, reference_notes,
   opening_prompt, hint_ladder, expected_follow_ups, optimal_complexity, rubric_dimensions, display_order)
VALUES

(NULL, 'coding', 'TCS',
 'FizzBuzz (https://leetcode.com/problems/fizz-buzz/) — print Fizz/Buzz/FizzBuzz for numbers 1 to n based on divisibility by 3 and 5.',
 'Easy',
 'TCS technical rounds for freshers are reported to focus on basic coding fluency and CS fundamentals rather than LeetCode-hard algorithms — simple, correctness-focused problems like this are representative. TCS also runs a separate aptitude/logical-reasoning section (NQT) that this platform does not cover.',
 'The four cases (div by 3, div by 5, div by both, neither) must all be handled correctly — check divisibility by 15 first.',
 'This is meant to be quick — checking basic coding fluency, not depth.',
 '["Think about what condition needs checking for each number.", "Check divisibility by 15 (both 3 and 5) before checking either alone."]',
 '[{"trigger":"after_first_working_solution","question":"What would change if you needed to check divisibility by four different numbers instead of two?"}]',
 'O(n) time, O(1) space',
 '[{"dimension":"correctness","description":"Are all four cases handled correctly?"},{"dimension":"code_clarity","description":"Is the code clean without unnecessary complexity for a simple problem?"}]',
 25),

(NULL, 'coding', 'TCS',
 'Reverse String (https://leetcode.com/problems/reverse-string/) — reverse a string in-place.',
 'Easy',
 'Basic string manipulation is a standard TCS fresher-round staple, per reported patterns — the bar is correctness and in-place handling, not algorithmic depth.',
 'Two pointers from both ends, swapping and moving inward, is the expected in-place approach.',
 'Keep it simple — walk through your approach before coding.',
 '["Two pointers starting from both ends can swap toward the middle.", "Stop when the pointers meet or cross."]',
 '[{"trigger":"after_first_working_solution","question":"Could you do this without any extra space at all?"}]',
 'O(n) time, O(1) space',
 '[{"dimension":"in_place_awareness","description":"Did they avoid creating a new string/array?"},{"dimension":"correctness","description":"Does it handle odd and even length strings correctly?"}]',
 26),

('str_palindrome', 'coding', 'Infosys',
 'Palindrome Number (https://leetcode.com/problems/palindrome-number/) — determine if an integer reads the same backward as forward, without converting to a string.',
 'Easy',
 'Infosys fresher rounds are reported to emphasize basic problem-solving and communication clarity over algorithmic difficulty — the "without converting to a string" constraint is the actual test here, not the palindrome logic itself.',
 'Reverse half the number mathematically (mod/divide) and compare to the remaining half.',
 'Notice the constraint here — no string conversion allowed. What does that push you toward?',
 '["Think about extracting digits mathematically using % and //.", "You only need to reverse half the digits to compare against the other half."]',
 '[{"trigger":"if_string_conversion_used","question":"Can you solve this using only arithmetic, without converting to a string?"}]',
 'O(log n) time, O(1) space',
 '[{"dimension":"constraint_respected","description":"Did they avoid string conversion as specified?"},{"dimension":"edge_cases","description":"Did they consider negative numbers or numbers ending in zero?"}]',
 27),

(NULL, 'coding', 'Infosys',
 'Remove Duplicates from Sorted Array (https://leetcode.com/problems/remove-duplicates-from-sorted-array/) — remove duplicates in-place from a sorted array, returning the new length.',
 'Easy',
 'A classic in-place array manipulation question reported across Infosys fresher rounds — the in-place, O(1)-space constraint is the actual point being tested.',
 'Two pointers: one scans, one marks the position for the next unique element.',
 'Walk through why sortedness matters here before you start.',
 '["Since the array is sorted, duplicates are always adjacent.", "Use a slow pointer for the next unique-element position and a fast pointer to scan."]',
 '[{"trigger":"after_first_working_solution","question":"What if the array were not sorted — would your approach still work?"}]',
 'O(n) time, O(1) extra space',
 '[{"dimension":"in_place_awareness","description":"Did they avoid extra array allocation?"},{"dimension":"uses_sortedness","description":"Did they explicitly use the fact that duplicates are adjacent?"}]',
 28),

('hash_map_basics', 'coding', 'Wipro',
 'Majority Element (https://leetcode.com/problems/majority-element/) — find the element appearing more than n/2 times in an array.',
 'Easy',
 'Wipro technical rounds are reported to test practical problem-solving with basic data structures — a hash-map frequency-count approach is the expected baseline here.',
 'A frequency map is the direct approach; Boyer-Moore voting is the O(1)-space follow-up.',
 'Start with whatever approach is clearest to you first.',
 '["A frequency count of each element is a direct starting point.", "Since the majority element appears more than half the time, is there a way to track it without extra space?"]',
 '[{"trigger":"after_first_working_solution","question":"Can you solve this in O(1) extra space instead of a hash map?"}]',
 'O(n) time, O(1) space with Boyer-Moore voting (O(n) space with a hash map)',
 '[{"dimension":"baseline_correct","description":"Does the hash-map approach work correctly first?"},{"dimension":"space_optimization","description":"Did they reach or attempt the O(1)-space approach when prompted?"}]',
 29),

('str_anagram', 'coding', 'Wipro',
 'Valid Anagram (https://leetcode.com/problems/valid-anagram/) — determine if one string is an anagram of another.',
 'Easy',
 'String and hashing fundamentals are reported as a common Wipro technical-round theme — this tests the same character-frequency thinking at a fresher-appropriate difficulty.',
 'Character frequency count, or sorting both strings and comparing.',
 'Explain your approach before writing any code.',
 '["Equal length is necessary but not sufficient — what else needs to match?", "A frequency count of characters in both strings is one direct approach."]',
 '[{"trigger":"if_only_checks_length","question":"Two strings can be the same length without being anagrams — what else do you need to check?"}]',
 'O(n) time, O(1) space (fixed alphabet)',
 '[{"dimension":"correctness","description":"Do they check frequency, not just length?"},{"dimension":"approach_clarity","description":"Did they explain the approach before coding?"}]',
 30),

('hash_map_basics', 'coding', 'Flipkart',
 'Two Sum (https://leetcode.com/problems/two-sum/) — find two numbers in an array that add up to a target.',
 'Easy',
 'Flipkart is reported to run genuine DSA coding rounds at medium difficulty for product-engineering roles — this is a common warm-up before harder problems in that loop.',
 'A hash map storing value-to-index lets you check for the complement in one pass.',
 'Start with the brute force if that is where your head is, then we will optimize.',
 '["The brute force checks every pair — what is its complexity?", "A hash map can store what you have seen so far, letting you check for a complement in one pass."]',
 '[{"trigger":"if_brute_force_only","question":"Your solution is O(n^2) — can you do this in one pass using a hash map?"}]',
 'O(n) time, O(n) space',
 '[{"dimension":"optimization_reached","description":"Did they move from brute force to the one-pass hash map approach?"},{"dimension":"edge_cases","description":"Did they consider duplicate values or no valid pair existing?"}]',
 31),

('hash_set', 'coding', 'Flipkart',
 'Contains Duplicate (https://leetcode.com/problems/contains-duplicate/) — determine if any value appears at least twice in an array.',
 'Easy',
 'A genuinely common Flipkart-reported warm-up question — straightforward, but the follow-up on space tradeoffs is where the real signal is.',
 'A hash set lets you check for duplicates in one pass with O(n) space; sorting first trades time for O(1) extra space.',
 'Tell me your approach before coding it.',
 '["A hash set can track values seen so far.", "Sorting the array first is an alternative that trades time for less extra space."]',
 '[{"trigger":"after_first_working_solution","question":"What is the time/space tradeoff between your hash set approach and sorting the array first?"}]',
 'O(n) time, O(n) space with a hash set (O(n log n) time, O(1) space if sorting first)',
 '[{"dimension":"correctness","description":"Does the base solution work correctly?"},{"dimension":"tradeoff_awareness","description":"Did they articulate the hash-set vs. sorting tradeoff when asked?"}]',
 32),

('arr_two_pointer', 'coding', 'Swiggy',
 '3Sum (https://leetcode.com/problems/3sum/) — find all unique triplets in an array that sum to zero.',
 'Medium',
 'Swiggy''s product-engineering interviews are reported to test genuine medium-difficulty DSA — this is a classic two-pointer extension question at that level.',
 'Sort first, fix one element, then two-pointer the rest — skip duplicates carefully to keep triplets unique.',
 'This builds on simpler two-pointer problems — walk through how you would extend that idea to three numbers.',
 '["Sorting the array first makes a two-pointer approach possible for the remaining two numbers.", "After fixing one number, this becomes a two-sum problem on the rest.", "Watch for and skip duplicate values to avoid repeated triplets."]',
 '[{"trigger":"if_duplicates_not_handled","question":"How do you avoid returning duplicate triplets in your result?"}]',
 'O(n^2) time, O(1) extra space (excluding sort)',
 '[{"dimension":"builds_on_two_sum","description":"Did they recognize this as fix-one-plus-two-pointer, not a brand new problem?"},{"dimension":"duplicate_handling","description":"Did they correctly avoid duplicate triplets in the output?"}]',
 33),

('arr_kadane', 'coding', 'Swiggy',
 'Best Time to Buy and Sell Stock (https://leetcode.com/problems/best-time-to-buy-and-sell-stock/) — maximize profit from one buy and one sell.',
 'Easy',
 'A single-pass array-tracking problem reported as a common Swiggy warm-up — tests whether a candidate reaches the O(n) single-pass insight rather than defaulting to checking every pair.',
 'Track the minimum price seen so far while scanning once, updating the best profit at each step.',
 'Start with the brute force approach, then we will see if it can be improved.',
 '["Checking every buy-sell pair works but is O(n^2) — what could you track in a single pass instead?", "Keep a running minimum price seen so far as you scan left to right."]',
 '[{"trigger":"if_brute_force_only","question":"Can you solve this in a single pass through the array?"}]',
 'O(n) time, O(1) space',
 '[{"dimension":"single_pass_reached","description":"Did they reach the O(n) single-pass solution?"},{"dimension":"edge_cases","description":"Did they consider a strictly decreasing price sequence (no profit possible)?"}]',
 34),

('arr_prefix_sum', 'coding', 'Paytm',
 'Subarray Sum Equals K (https://leetcode.com/problems/subarray-sum-equals-k/) — count contiguous subarrays summing to a target k.',
 'Medium',
 'A prefix-sum problem reported as a genuine Paytm-style medium question — fitting, given the payments-domain flavor of "running totals."',
 'Prefix sums with a hash map of frequencies, since negative numbers rule out a sliding-window approach.',
 'Think about why a sliding window would not work here before choosing your approach.',
 '["The array can contain negative numbers — does that rule out a sliding window?", "Track a running prefix sum and a hash map of how many times each prefix sum has occurred.", "At each step, check whether currentSum - k has been seen before."]',
 '[{"trigger":"if_sliding_window_attempted","question":"Why does sliding window not work here, given the array can contain negative numbers?"}]',
 'O(n) time, O(n) space',
 '[{"dimension":"recognizes_negative_number_issue","description":"Did they recognize why sliding window fails with negative numbers present?"},{"dimension":"prefix_sum_reasoning","description":"Did they correctly explain the prefixSum - k lookup logic?"}]',
 35),

('sq_stack_basics', 'coding', 'Paytm',
 'Valid Parentheses (https://leetcode.com/problems/valid-parentheses/) — determine if a string of brackets is validly nested.',
 'Easy',
 'A classic stack-based validation question reported across Indian product-company interviews — fits a payments company''s need to validate structured, nested data like transaction receipts.',
 'A stack tracks open brackets; each closing bracket must match the most recent unmatched opening bracket.',
 'Walk through what data structure naturally fits "most recent unmatched thing" before coding.',
 '["What structure naturally gives you access to the most recently opened, still-unmatched bracket?", "Push opening brackets onto a stack; on a closing bracket, check it matches the top of the stack."]',
 '[{"trigger":"after_first_working_solution","question":"What happens if the string has a closing bracket with an empty stack — does your solution handle that?"}]',
 'O(n) time, O(n) space',
 '[{"dimension":"correctness","description":"Does it correctly reject mismatched or unbalanced brackets?"},{"dimension":"edge_cases","description":"Did they handle an empty string or a lone closing bracket without crashing?"}]',
 36);

-- VERIFICATION QUERY — expect 12 new rows across 6 companies
SELECT company, count(*) FROM interview_questions
WHERE display_order >= 25
GROUP BY company ORDER BY company;
